# Generated by Django 5.1.1 on 2024-09-23 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30)),
                ('what', models.CharField(max_length=30)),
                ('why', models.TextField()),
                ('where', models.CharField(max_length=60)),
                ('when', models.DateField()),
                ('who', models.CharField(max_length=30)),
                ('how', models.TextField()),
                ('how_much', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
    ]
