# Generated by Django 5.1.1 on 2024-09-11 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastro_cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('sobrenome', models.CharField(max_length=30)),
                ('cpf', models.CharField(max_length=14)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Cadastro_marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_marca', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Cadastro_de_produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('descricao', models.CharField(max_length=100)),
                ('custo', models.DecimalField(decimal_places=2, max_digits=8)),
                ('preco_venda', models.DecimalField(decimal_places=2, max_digits=8)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_venda_produtos.cadastro_marca')),
            ],
        ),
        migrations.CreateModel(
            name='Vendas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_tootal', models.DecimalField(decimal_places=2, max_digits=8)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_venda_produtos.cadastro_cliente')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_venda_produtos.cadastro_de_produto')),
            ],
        ),
    ]
